# Must match what you set in SonarCloud dashboard
sonar.projectKey=sudha3636_cicd-pipeline-project-
sonar.organization=sudha3636
sonar.host.url=https://sonarcloud.io

# Project info
sonar.projectName=cicd-pipeline-project-
sonar.projectVersion=1.0.0

# Source and test paths
sonar.sources=src/main/java
sonar.tests=src/test/java

# Java specific
sonar.java.source=17
sonar.java.target=17
sonar.language=java
sonar.java.binaries=target/classes

# JaCoCo coverage report — this is what SonarCloud reads
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions — do not analyse these
sonar.exclusions=**/Application.java,**/*Test*.java,**/model/**
sonar.test.inclusions=**/*Test*.java
